#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build 360T7 Immortalwrt 24.10-6.6

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: openwrt-24.10-6.6
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 360t7-24.10-6.6-pw2-mosdns-tailscale.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: 360t7-24.10-6.6-pw2-mosdns-tailscale.sh
  RELEASE_FILE: 360t7-24.10-6.6-pw2-mosdns-tailscale.md
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    uses: ./.github/workflows/image-builder.yml
    with:
      repo_url: ${{ env.REPO_URL }}
      repo_branch: ${{ env.REPO_BRANCH }}
      feeds_conf: ${{ env.FEEDS_CONF }}
      config_file: ${{ env.CONFIG_FILE }}
      diy_p1_sh: ${{ env.DIY_P1_SH }}
      diy_p2_sh: ${{ env.DIY_P2_SH }}
      release_file: ${{ env.RELEASE_FILE }}
      upload_bin_dir: ${{ env.UPLOAD_BIN_DIR }}
      upload_firmware: ${{ env.UPLOAD_FIRMWARE }}
      upload_release: ${{ env.UPLOAD_RELEASE }}
      tz: ${{ env.TZ }}

